# Randomize
Load a dataset as a prefab, randomize selected columns and save as `csv`.

In [5]:
import pandas as pd
import numpy as np

# Reads a dataset and saves a randomized version.
# file: string path
# columns: list of tuples (column name, range of values)
def read_and_randomize(file, columns):
    df = pd.read_csv(file, encoding="latin_1")
    
    # for each selected column
    for (col, vals) in columns:
        rand_vals = []
        
        # generate random samples
        for line in df[col]:
            rand_vals.append(vals[np.random.randint(0, len(vals))])
        
        df[col] = pd.Series(rand_vals)
        
    index = file.find('.csv')
    file = file[:index] + '_random' + file[index:]
    df.to_csv(file, index=False)
    display(df)
        
cols = [('Q1', np.arange(1, 8)), ('Q2', np.arange(1, 8)), ('Q3', np.arange(1, 8)), ('Q4', np.arange(1, 8))]
cols.append(('Condition', ('XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL')))
cols.append(('Task', np.arange(1, 3)))
cols.append(('Participant', np.arange(1, 15)))
read_and_randomize("tables/results.csv", cols)

     Participant  Task Condition  Q1  Q2  Q3  Q4
0             13     1         S   3   6   2   2
1             13     1         M   3   2   5   6
2              1     2       XXS   3   4   2   7
3              3     1        XL   7   4   1   4
4              2     1       XXS   4   2   5   2
..           ...   ...       ...  ..  ..  ..  ..
191            8     2         M   5   3   4   7
192            7     1       XXS   4   5   2   1
193            4     1         L   5   5   2   6
194            8     2        XS   7   4   5   4
195            4     1         S   1   3   6   4

[196 rows x 7 columns]